// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKnqkV95vrJ4fI6tF7Tk4-n42KgmmP3U',
    appId: '1:806367836520:web:a098b1bcaf76f97435bedd',
    messagingSenderId: '806367836520',
    projectId: 'todoapp-cb281',
    authDomain: 'todoapp-cb281.firebaseapp.com',
    storageBucket: 'todoapp-cb281.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7el7XNDeVad22xBnZKZCDnutsokq5tzo',
    appId: '1:806367836520:android:200d3e2c91775e1635bedd',
    messagingSenderId: '806367836520',
    projectId: 'todoapp-cb281',
    storageBucket: 'todoapp-cb281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZpKpdXQsgcKZtGfoVtRr37gL5dhR6eU',
    appId: '1:806367836520:ios:252fcf121c71224935bedd',
    messagingSenderId: '806367836520',
    projectId: 'todoapp-cb281',
    storageBucket: 'todoapp-cb281.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZpKpdXQsgcKZtGfoVtRr37gL5dhR6eU',
    appId: '1:806367836520:ios:252fcf121c71224935bedd',
    messagingSenderId: '806367836520',
    projectId: 'todoapp-cb281',
    storageBucket: 'todoapp-cb281.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNKnqkV95vrJ4fI6tF7Tk4-n42KgmmP3U',
    appId: '1:806367836520:web:7e236c46278c8de435bedd',
    messagingSenderId: '806367836520',
    projectId: 'todoapp-cb281',
    authDomain: 'todoapp-cb281.firebaseapp.com',
    storageBucket: 'todoapp-cb281.firebasestorage.app',
  );
}
